[sncast.default]
url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_8/0RgYg5kE6gnVxXwAKUKuW"
accounts-file = "accounts.json"
account = "js"
chain_id = "SN_SEPOLIA"
show-explorer-links = true
